GET http://localhost:3335/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsbmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRoRVQ2V09sTkxFTFJZU0ZrLkk1TGF1ZGJXb2w2dEpDNmR1L2NMOWVaeUcuc1A4WGJEVkpjdSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjVlMjE2MWU4OTBjYjE3MTNiYzYwMTgwNyIsImlhdCI6MTU4MDcyMTAzOCwiZXhwIjoxNTgwNzM5MDM4fQ.67powuNmN777_GsimSex1oxgdwrLETzw17WzkjeFU6M

###
POST http://localhost:3335/admin/
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password": "admin123"
}

###
GET  http://localhost:3335/admin/init

###
GET  http://localhost:3335/admin/test

###
POST http://localhost:3335/admin/signIn 
Content-Type: application/json

{
    "fullname": "dang quang vu",
    "email": "dangquangvu999@gmail.com",
    "password": "admin"
}

###
POST  http://localhost:3335/admin/get_message
Content-Type: application/json

###
POST  http://localhost:3335/admin/send_message
Content-Type: application/json

{
    "conversationId": "5e3a8572fc96532a9462f0ec",
    "body": "aaa",
    "author" : "5e2161e890cb1713bc601807",
    "nameAuthor": "admin"
}

###
POST  http://localhost:3335/admin/send_message
Content-Type: application/json

{
    "conversationId": "5e3a8572fc96532a9462f0ec",
    "body": "bbb",
    "author" : "5e215ed8134dd8176cc03f57",
    "nameAuthor": "dang quang vu"
}


###
POST  http://localhost:3335/admin/conversation
Content-Type: application/json

{
    "nameConversation": "Dang Thi Ngoc Tram",
    "participants" : ["5e21644290cb1713bc601808","5e215ed8134dd8176cc03f57"]
}
//5e3a8572fc96532a9462f0ec

###
POST  "http://localhost:3335/admin/conversationId"
Content-Type: application/json

{
    "nameConversation": "dang quang vu"
}