GET http://localhost:3334/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmd2dTk5ODFAZ21haWwuY29tIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTU3ODM4MjMzOSwiZXhwIjoxNTc4Mzg1OTM5fQ.7gqzBans3WVT02rDeCAtK0ODmWySTctVpMCGy-ipU6M


###
POST http://localhost:3334/admin/
Content-Type: application/json

{
    "email" : "dangvu9981@gmail.com",
    "password": "admin"
}
###
GET  http://localhost:3334/admin/init

###
POST http://localhost:3334/admin/init
Content-Type: application/json

{
    "fullname": "dang tuan phat",
    "email": "dangvu9981@gmail.com",
    "password": "admin"
}